app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /
    
app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:list }

app_details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:Default:details }    